### ISSUE TITLE
social authentication integration

### ISSUE THREAD

**Issue by althaffe** [rlindskog/vueniverse#15]
The email+pwd only auth is pretty limiting for current scenarios. It'd have been great if an oauth integration for at least google, fb and twitter were baked in. Any chance of this coming anytime soon? I'm struggling a bit on that part. Any help is appreciated

**Comment by Prozi** [comment]
try to checkout hackathon starter project (https://github.com/sahat/hackathon-starter) its built exactly for that

as for my 2 cents I'd keep this project slim & lean but who knows what would be best for future

**Comment by althaffe** [comment]
Okay cool. I'll close this for now. But still hoping at least a simple implementation
