### ISSUE TITLE
JWT Token in Cookie

### ISSUE THREAD

**Issue by ansarizafar** [rlindskog/vueniverse#5]
Could you please show me where you are setting token as cookie. I can't see it in Sigin.post route handler.

**Comment by rlindskog** [comment]
@ansarizafar The token is being signed in [signIn.post](https://github.com/rlindskog/vueniverse/blob/master/template/src/server/api/users/controllers.js), return to the client as a JSON response, and the client is setting it as a cookie in [store/user.js](https://github.com/rlindskog/vueniverse/blob/master/template/src/client/store/user.js), specifically the  `SIGN_IN_SUCCESS` mutation.

**Comment by rlindskog** [comment]
@ansarizafar Let me know if you have any other questions.
