### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by gregbenner** [rlindskog/vueniverse#7]
node -v
v8.0.0
 npm -v
5.3.0
`DONE  Compiled successfully in 403ms`
`(node:14125) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: __WEBPACK_IMPORTED_MODULE_6_nuxt___default.a is not a constructor`

**Comment by rlindskog** [comment]
Thanks! Fixed by updating Nuxt and updating `src/server/index.js` to reflect its new programatic API.
